# Copyright (c) 2025 RockBase-IoT, Chengdu Rockbase Co., Ltd. All rights reserved.
"""
gen_embedded_page.py — PlatformIO extra_script (pre-build hook)

Gzip web/uploader.html and generate src/net/embedded_page.h:
    - EMBEDDED_PAGE_GZIP      byte array
    - EMBEDDED_PAGE_GZIP_LEN  length
The output file is not rewritten when content is unchanged, to avoid
triggering a full rebuild.

Can also run standalone:  python scripts/gen_embedded_page.py
"""

import gzip
import hashlib
import os

try:
    Import("env")   # noqa: F821
    PROJECT_DIR = env.subst("$PROJECT_DIR")
except Exception:  # standalone
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC = os.path.join(PROJECT_DIR, "web", "uploader.html")
DST = os.path.join(PROJECT_DIR, "src", "net", "embedded_page.h")


def generate():
    with open(SRC, "rb") as f:
        raw = f.read()
    blob = gzip.compress(raw, compresslevel=9, mtime=0)

    lines = []
    for i in range(0, len(blob), 16):
        lines.append("    " + ", ".join("0x%02x" % b for b in blob[i:i + 16]) + ",")

    out = (
        "// AUTO-GENERATED by scripts/gen_embedded_page.py — DO NOT EDIT.\n"
        "// Source: web/uploader.html (gzip -9, mtime=0 for reproducibility)\n"
        "#pragma once\n"
        "#include <Arduino.h>\n\n"
        "static const uint8_t EMBEDDED_PAGE_GZIP[] PROGMEM = {\n"
        + "\n".join(lines) +
        "\n};\n"
        "static const uint32_t EMBEDDED_PAGE_GZIP_LEN = %d;\n" % len(blob)
    )

    if os.path.isfile(DST):
        with open(DST, "r", encoding="utf-8") as f:
            if f.read() == out:
                return
    os.makedirs(os.path.dirname(DST), exist_ok=True)
    with open(DST, "w", encoding="utf-8") as f:
        f.write(out)
    print("[page] embedded_page.h regenerated: %d B html -> %d B gzip (sha1 %s)"
          % (len(raw), len(blob), hashlib.sha1(raw).hexdigest()[:8]))


generate()
