# Copyright (c) 2025 RockBase-IoT, Chengdu Rockbase Co., Ltd. All rights reserved.
"""
gen_embedded_page.py — PlatformIO extra_script (pre-build hook)

Inline the page's sibling scripts into web/uploader.html, then gzip the result
and generate src/net/embedded_page.h:
    - EMBEDDED_PAGE_GZIP      byte array
    - EMBEDDED_PAGE_GZIP_LEN  length
The output file is not rewritten when content is unchanged, to avoid
triggering a full rebuild.

Why inline instead of serving the scripts from their own routes: the firmware
serves exactly one HTML blob, and retro_core.js must reach the browser with the
page that uses it. Inlining keeps the build a single artefact and needs no extra
route or extra PROGMEM table. The source stays two files on disk so the page can
still be opened directly from the filesystem during development.

Any `<script src="...">` whose target is a sibling file of uploader.html is
replaced in place with
    <script>/* inlined: <name> */ ...contents...</script>
Leave a `<script src>` alone (i.e. give it an http(s) URL) if it must stay
external. A missing sibling is a build error, not a warning - silently shipping
a page that 404s its own quantizer would be worse than failing the build.

Can also run standalone:  python scripts/gen_embedded_page.py
"""

import gzip
import hashlib
import os
import re

try:
    Import("env")   # noqa: F821
    PROJECT_DIR = env.subst("$PROJECT_DIR")
except Exception:  # standalone
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WEB_DIR = os.path.join(PROJECT_DIR, "web")
SRC = os.path.join(WEB_DIR, "uploader.html")
DST = os.path.join(PROJECT_DIR, "src", "net", "embedded_page.h")

# <script src="foo.js"></script> — capture the src, tolerate attribute order and
# single or double quotes on the src value.
SCRIPT_SRC_RE = re.compile(
    r"""<script\b[^>]*\bsrc\s*=\s*["']([^"'>]+)["'][^>]*>\s*</script>""",
    re.IGNORECASE,
)


def inline_scripts(html):
    """Replace every sibling-file <script src> with the file's contents."""
    inlined = []

    def repl(m):
        src = m.group(1)
        if "://" in src or src.startswith("//") or src.startswith("data:"):
            return m.group(0)          # external or inline already; leave it
        target = os.path.join(WEB_DIR, src)
        if not os.path.isfile(target):
            raise SystemExit(
                "[page] FAIL: %s references %s but that file does not exist"
                % (os.path.basename(SRC), src))
        with open(target, "r", encoding="utf-8") as f:
            body = f.read()
        # Guard the closing-tag sequence: a literal "</script>" inside the JS
        # would terminate the <script> element early and break the page.
        if "</script" in body.lower():
            raise SystemExit(
                "[page] FAIL: %s contains a literal </script> — split it, or the"
                " inlined block will be terminated early" % src)
        inlined.append(src)
        return "<script>/* inlined: %s */\n%s\n</script>" % (src, body)

    return SCRIPT_SRC_RE.sub(repl, html), inlined


def generate():
    with open(SRC, "rb") as f:
        raw = f.read()

    html, inlined = inline_scripts(raw.decode("utf-8"))
    if inlined:
        print("[page] inlined: %s" % ", ".join(inlined))

    blob = gzip.compress(html.encode("utf-8"), compresslevel=9, mtime=0)

    lines = []
    for i in range(0, len(blob), 16):
        lines.append("    " + ", ".join("0x%02x" % b for b in blob[i:i + 16]) + ",")

    out = (
        "// AUTO-GENERATED by scripts/gen_embedded_page.py — DO NOT EDIT.\n"
        "// Source: web/uploader.html%s (gzip -9, mtime=0 for reproducibility)\n"
        % (("  +  " + ", ".join(inlined)) if inlined else "") +
        "#pragma once\n"
        "#include <Arduino.h>\n\n"
        "static const uint8_t EMBEDDED_PAGE_GZIP[] PROGMEM = {\n"
        + "\n".join(lines) +
        "\n};\n"
        "static const uint32_t EMBEDDED_PAGE_GZIP_LEN = %d;\n" % len(blob)
    )

    if os.path.isfile(DST):
        with open(DST, "r", encoding="utf-8") as f:
            if f.read() == out:
                return
    os.makedirs(os.path.dirname(DST), exist_ok=True)
    with open(DST, "w", encoding="utf-8") as f:
        f.write(out)
    print("[page] embedded_page.h regenerated: %d B html (%d B inlined) -> %d B gzip (sha1 %s)"
          % (len(raw), len(html), len(blob), hashlib.sha1(html.encode("utf-8")).hexdigest()[:8]))


generate()
